#!/usr/bin/env ruby
# frozen_string_literal: true

module Verify
  module Reason
    OK = 'OK'

    NO_ADVERTISEMENTS = 'NO_ADVERTISEMENTS'
    ADVERTISEMENT_GAP_EXCEEDED = 'ADVERTISEMENT_GAP_EXCEEDED'
    NO_DEVICES_FOUND = 'NO_DEVICES_FOUND'
    NO_NAMED_DEVICES = 'NO_NAMED_DEVICES'

    NO_CONNECTABLE_DEVICES = 'NO_CONNECTABLE_DEVICES'
    COULD_NOT_CONNECT = 'COULD_NOT_CONNECT'
    SESSION_CLOSED = 'SESSION_CLOSED'

    SKIP_NO_CONNECTABLE_DEVICES = 'SKIP_NO_CONNECTABLE_DEVICES'
    SKIP_NO_SUBSCRIBABLE_CHARACTERISTICS = 'SKIP_NO_SUBSCRIBABLE_CHARACTERISTICS'
    SKIP_NO_NOTIFICATIONS = 'SKIP_NO_NOTIFICATIONS'

    NO_DATA_POINTS = 'NO_DATA_POINTS'
    STREAM_GAP_EXCEEDED = 'STREAM_GAP_EXCEEDED'
    CONNECTION_DROPPED = 'CONNECTION_DROPPED'

    TIMEOUT = 'TIMEOUT'
    EXCEPTION = 'EXCEPTION'
    THREAD_LEAK = 'THREAD_LEAK'
    FD_LEAK = 'FD_LEAK'
  end
end
